### PR TITLE
austria and canada gov fixing

### LINKED ISSUE #913: Use proxy for Austria request
Log from production scraper

```
[2020-10-09T15:33:20.604Z]: Austria scraper has failed. (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm] { (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm]   message: '[2020-10-09T15:33:20.597Z] ERROR: Error: Requesting Austria Gov Data failed!', (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm]   error: 'connect ECONNRESET 194.48.237.240:443', (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm]   stack: 'Error: connect ECONNRESET 194.48.237.240:443\n' + (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm]     '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)' (B[m
(B[m[(B[m(B[mnovelcovid.scraper-79bd4d96df-cp7dm] } (B[m
```

### PR DESCRIPTION
**Pull request by puf17640**
not sure if austria is fixed now, we will have to see if it works in production (I just changed https to http and it worked fine on local)

canada scraper was fucked so I "fixed" it by removing the filtration

closes #913

### CODE REVIEW

**Comment by puf17640** [comment]
should close #913

File: scrapers/covid-19/govScrapers/getCanada.js [hunk 1]
```diff
@@ -20,10 +21,18 @@ const canadaData = async () => {
...
 			province: province.prname === 'Canada' ? 'Total' : province.prname,
+			date: province.date,
+			todayCases: parseInt(province.numtoday) || 0,
+			todayTests: parseInt(province.numtestedtoday) || 0,
+			todayRecovered: parseInt(province.numrecoveredtoday) || 0,
+			todayDeaths: parseInt(province.numdeathstoday) || 0,
 			cases: parseInt(province.numconf) || 0,
+			active: parseInt(province.numactive) || 0,
+			tests: parseInt(province.numtested) || 0,
+			recovered: parseInt(province.numrecover) || 0,
```
Comment (ebwinters) [inline scrapers/covid-19/govScrapers/getCanada.js:35]: instead of 0s we should put `nulls` or nothing, otherwise we report incorrect data

File: tests/v3/covid-19/api_gov.spec.js [hunk 2]
```diff
@@ -46,28 +46,25 @@ describe('TESTING /v3/covid-19/gov general', () => {
...
-				done();
-			});
-	});
-
 	it('/v3/covid-19/gov/canada correct fields set', (done) => {
 		chai.request(app)
 			.get('/v3/covid-19/gov/canada')
 			.end((err, res) => {
 				testBasicProperties(err, res, 200, 'array');
+				res.body.length.should.at.greater.or.equal(1);
```
Comment (ebwinters) [inline tests/v3/covid-19/api_gov.spec.js:54]: incorrect syntax: this is why your tests are failing -- it should be:
`(xxx).should.be.above(yyy);`

File: scrapers/covid-19/govScrapers/getCanada.js (hunk 1 above)
Comment (puf17640) [reply scrapers/covid-19/govScrapers/getCanada.js:35]: yeah true, I just went with what was already done by collin, but good idea

File: tests/v3/covid-19/api_gov.spec.js (hunk 2 above)
Comment (puf17640) [reply tests/v3/covid-19/api_gov.spec.js]: no idea what i thought when pushing this, must have been quite in a rush

**Review by ebwinters — APPROVED** [review]
